--######################
--## HYPRLAND CONFIG ###
--######################

-- Please note not all available settings / options are set here.
-- For a full list, see the wiki

-- You can split this configuration into multiple files
-- Create your files separately and then link them to this file like this:
-- source = ~/.config/hypr/myColors.conf

--###############
--## MONITORS ###
--###############

-- See https://wiki.hyprland.org/Configuring/Monitors/
--monitor=,2560x1440@144,auto,auto
-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.monitor({
  output = "",
  mode = "preferred",
  position = "auto",
  scale = "auto",
})

hl.monitor({
  output = "DP-8",
  mode = "preferred",
  position = "-2560x-800",
  scale = "auto",
})

hl.monitor({
  output = "DP-9",
  mode = "preferred",
  position = "-2560x-800",
  scale = "auto",
})

hl.monitor({
  output = "DP-7",
  mode = "preferred",
  position = "-2560x-800",
  scale = "auto",
  disabled = false,
  -- sdrbrightness = 0.2
  -- sdrsaturation = 0.2
  -- cm = hdr
})

--##################
--## MY PROGRAMS ###
--##################

-- See https://wiki.hyprland.org/Configuring/Keywords/

-- Set programs that you use
-- $terminal = kitty
local terminal = "ghostty"
local fileManager = "dolphin"
local menu = "wofi --show drun"

--############################
--## ENVIRONMENT VARIABLES ###
--############################

-- See https://wiki.hyprland.org/Configuring/Environment-variables/

-- Set cursor size
hl.env("HYPRCURSOR_SIZE", "20")
-- env = HYPRCURSOR_THEME,/home/mqngo/.local/share/icons/cursor-theme
hl.env("HYPRCURSOR_THEME", "/run/current-system/sw/share/icons/catppuccin-mocha-lavender-cursors")

-- Set hyprshot save directory
hl.env("HYPRSHOT_DIR", "/home/mqngo/Pictures/screenshots")

-- env = AQ_DRM_DEVICES, /dev/dri/card1:/dev/dri/card0
-- env = AQ_DRM_DEVICES, /dev/dri/card1

--##################
--## PERMISSIONS ###
--##################

-- See https://wiki.hyprland.org/Configuring/Permissions/
-- Please note permission changes here require a Hyprland restart and are not applied on-the-fly
-- for security reasons

-- ecosystem {
--   enforce_permissions = 1
-- }

-- permission = /usr/(bin|local/bin)/grim, screencopy, allow
-- permission = /usr/(lib|libexec|lib64)/xdg-desktop-portal-hyprland, screencopy, allow
-- permission = /usr/(bin|local/bin)/hyprpm, plugin, allow

--####################
--## LOOK AND FEEL ###
--####################

-- Refer to https://wiki.hyprland.org/Configuring/Variables/

-- https://wiki.hyprland.org/Configuring/Variables/#general

-- Load the color theme
-- Source: ~/.config/hypr/themes/catppuccin/mocha.conf — convert this file to Lua and ensure it is on Lua's package.path.
local colors = require("themes.catppuccin-mocha")

hl.curve("easeOutQuint", { type = "bezier", points = { { 0.23, 1 }, { 0.32, 1 } } })
hl.curve("easeInOutCubic", { type = "bezier", points = { { 0.65, 0.05 }, { 0.36, 1 } } })
hl.curve("linear", { type = "bezier", points = { { 0, 0 }, { 1, 1 } } })
hl.curve("almostLinear", { type = "bezier", points = { { 0.5, 0.5 }, { 0.75, 1.0 } } })
hl.curve("quick", { type = "bezier", points = { { 0.15, 0 }, { 0.1, 1 } } })
hl.animation({
  leaf = "global",
  enabled = true,
  speed = 10,
  bezier = "default",
})
hl.animation({
  leaf = "border",
  enabled = true,
  speed = 5.39,
  bezier = "quick",
})
hl.animation({ leaf = "windows", enabled = true, speed = 4.1, bezier = "easeInOutCubic", style = "gnomed" })
hl.animation({
  leaf = "fadeIn",
  enabled = true,
  speed = 1.73,
  bezier = "almostLinear",
})
hl.animation({
  leaf = "fadeOut",
  enabled = true,
  speed = 1.46,
  bezier = "almostLinear",
})
hl.animation({
  leaf = "fade",
  enabled = true,
  speed = 3.03,
  bezier = "quick",
})
hl.animation({
  leaf = "layers",
  enabled = true,
  speed = 3.81,
  bezier = "easeOutQuint",
})
hl.animation({
  leaf = "layersIn",
  enabled = true,
  speed = 4,
  bezier = "easeOutQuint",
  style = "fade",
})
hl.animation({
  leaf = "layersOut",
  enabled = true,
  speed = 1.5,
  bezier = "linear",
  style = "fade",
})
hl.animation({
  leaf = "fadeLayersIn",
  enabled = true,
  speed = 1.79,
  bezier = "almostLinear",
})
hl.animation({
  leaf = "fadeLayersOut",
  enabled = true,
  speed = 1.39,
  bezier = "almostLinear",
})
hl.animation({
  leaf = "workspaces",
  enabled = true,
  speed = 2.71,
  bezier = "almostLinear",
  style = "fade",
})
hl.animation({
  leaf = "workspacesIn",
  enabled = true,
  speed = 1.94,
  bezier = "almostLinear",
  style = "fade",
})

hl.device({
  name = "epic-mouse-v1",
  sensitivity = -0.5,
})

--##################
--## KEYBINDINGS ###
--##################

local mainMod = "ALT" -- Sets ALT key as main modifier

hl.bind(mainMod .. " + RETURN", hl.dsp.exec_cmd(terminal))
hl.bind(mainMod .. " + W", hl.dsp.exec_cmd("librewolf"))
hl.bind(mainMod .. " + Q", hl.dsp.window.close())
hl.bind(mainMod .. " + SHIFT + M", hl.dsp.exit())
hl.bind(mainMod .. " + SHIFT + L", hl.dsp.exec_cmd("hyprlock"))
hl.bind(mainMod .. " + E", hl.dsp.exec_cmd(fileManager))
hl.bind(mainMod .. " + V", hl.dsp.window.float({ action = "toggle" }))
hl.bind(mainMod .. " + R", hl.dsp.exec_cmd(menu))
hl.bind(mainMod .. " + P", hl.dsp.layout("togglesplit"))
hl.bind(mainMod .. " + BACKSPACE", hl.dsp.exec_cmd("fnottctl dismiss"))
-- hl.bind(mainMod .. " + F", hl.dsp.window.fullscreen({ mode = "", action = "toggle" }))

hl.bind("PRINT", hl.dsp.exec_cmd("hyprshot -m region"))
hl.bind("SHIFT + PRINT", hl.dsp.exec_cmd("hyprshot -m output"))

hl.bind(mainMod .. " + B", hl.dsp.exec_cmd("lua ~/.config/hypr/otherCycle.lua"))

hl.bind(mainMod .. " + left", hl.dsp.focus({ direction = "left" }))
hl.bind(mainMod .. " + h", hl.dsp.focus({ direction = "left" }))
hl.bind(mainMod .. " + right", hl.dsp.focus({ direction = "right" }))
hl.bind(mainMod .. " + l", hl.dsp.focus({ direction = "right" }))
hl.bind(mainMod .. " + up", hl.dsp.focus({ direction = "up" }))
hl.bind(mainMod .. " + k", hl.dsp.focus({ direction = "up" }))
hl.bind(mainMod .. " + down", hl.dsp.focus({ direction = "down" }))
hl.bind(mainMod .. " + j", hl.dsp.focus({ direction = "down" }))

hl.bind(mainMod .. " + 1", hl.dsp.focus({ workspace = 1 }))
hl.bind(mainMod .. " + 2", hl.dsp.focus({ workspace = 2 }))
hl.bind(mainMod .. " + 3", hl.dsp.focus({ workspace = 3 }))
hl.bind(mainMod .. " + 4", hl.dsp.focus({ workspace = 4 }))
hl.bind(mainMod .. " + 5", hl.dsp.focus({ workspace = 5 }))
hl.bind(mainMod .. " + 6", hl.dsp.focus({ workspace = 6 }))
hl.bind(mainMod .. " + 7", hl.dsp.focus({ workspace = 7 }))
hl.bind(mainMod .. " + 8", hl.dsp.focus({ workspace = 8 }))
hl.bind(mainMod .. " + 9", hl.dsp.focus({ workspace = 9 }))
hl.bind(mainMod .. " + 0", hl.dsp.focus({ workspace = 10 }))

hl.bind(mainMod .. " + Tab", hl.dsp.focus({ workspace = "e+1" }))
hl.bind(mainMod .. " + SHIFT + Tab", hl.dsp.focus({ workspace = "e-1" }))

hl.bind(mainMod .. " + SHIFT + 1", hl.dsp.window.move({ workspace = 1 }))
hl.bind(mainMod .. " + SHIFT + 2", hl.dsp.window.move({ workspace = 2 }))
hl.bind(mainMod .. " + SHIFT + 3", hl.dsp.window.move({ workspace = 3 }))
hl.bind(mainMod .. " + SHIFT + 4", hl.dsp.window.move({ workspace = 4 }))
hl.bind(mainMod .. " + SHIFT + 5", hl.dsp.window.move({ workspace = 5 }))
hl.bind(mainMod .. " + SHIFT + 6", hl.dsp.window.move({ workspace = 6 }))
hl.bind(mainMod .. " + SHIFT + 7", hl.dsp.window.move({ workspace = 7 }))
hl.bind(mainMod .. " + SHIFT + 8", hl.dsp.window.move({ workspace = 8 }))
hl.bind(mainMod .. " + SHIFT + 9", hl.dsp.window.move({ workspace = 9 }))
hl.bind(mainMod .. " + SHIFT + 0", hl.dsp.window.move({ workspace = 10 }))

hl.bind(mainMod .. " + S", hl.dsp.workspace.toggle_special("magic"))
hl.bind(mainMod .. " + SHIFT + S", hl.dsp.window.move({ workspace = "special:magic" }))

hl.bind(mainMod .. " + mouse_down", hl.dsp.focus({ workspace = "e+1" }))
hl.bind(mainMod .. " + mouse_up", hl.dsp.focus({ workspace = "e-1" }))

hl.bind(mainMod .. " + mouse:272", hl.dsp.window.drag())
hl.bind(mainMod .. " + SHIFT + mouse:272", hl.dsp.window.resize())

local primary_player = "spotify"

hl.bind("CONTROL + SHIFT + left", hl.dsp.exec_cmd("playerctl --player " .. primary_player .. " previous"))
hl.bind("CONTROL + SHIFT + right", hl.dsp.exec_cmd("playerctl --player " .. primary_player .. " next"))
hl.bind("CONTROL + SHIFT + down", hl.dsp.exec_cmd("playerctl --player " .. primary_player .. " play-pause"))

hl.bind(mainMod .. " + CONTROL + left", hl.dsp.exec_cmd("playerctl --player " .. primary_player .. " previous"))
hl.bind(mainMod .. " + CONTROL + right", hl.dsp.exec_cmd("playerctl --player $primary_playe next"))
hl.bind(mainMod .. " + CONTROL + down", hl.dsp.exec_cmd("playerctl --player " .. primary_player .. " play-pause"))

hl.bind("XF86AudioNext", hl.dsp.exec_cmd("playerctl --player " .. primary_player .. " next"), { locked = true })
hl.bind("XF86AudioPause", hl.dsp.exec_cmd("playerctl --player " .. primary_player .. " play-pause"), { locked = true })
hl.bind("XF86AudioPlay", hl.dsp.exec_cmd("playerctl --player " .. primary_player .. " play-pause"), { locked = true })
hl.bind("XF86AudioPrev", hl.dsp.exec_cmd("playerctl --player " .. primary_player .. " previous"), { locked = true })

hl.bind("SUPER + t", hl.dsp.exec_cmd("sudo /home/mqngo/.scripts/toggleLayout.pl"))

hl.bind(
  "XF86AudioRaiseVolume",
  hl.dsp.exec_cmd("wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+"),
  { locked = true, repeating = true }
)
hl.bind(
  "XF86AudioLowerVolume",
  hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"),
  { locked = true, repeating = true }
)
hl.bind(
  "XF86AudioMute",
  hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"),
  { locked = true, repeating = true }
)
hl.bind(
  "XF86AudioMicMute",
  hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle"),
  { locked = true, repeating = true }
)
hl.bind("XF86MonBrightnessUp", hl.dsp.exec_cmd("brightnessctl -e2 -n4 set 5%+"), { locked = true, repeating = true })
hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd("brightnessctl -e2 -n4 set 5%-"), { locked = true, repeating = true })

--#############################
--## WINDOWS AND WORKSPACES ###
--#############################

hl.workspace_rule({
  workspace = "1",
  monitor = "eDP-1",
})

hl.workspace_rule({
  workspace = "2",
  monitor = "eDP-1",
})

hl.workspace_rule({
  workspace = "3",
  monitor = "eDP-1",
})

hl.workspace_rule({
  workspace = "4",
  monitor = "eDP-1",
})

hl.workspace_rule({
  workspace = "5",
  monitor = "eDP-1",
})

hl.workspace_rule({
  workspace = "6",
  monitor = "eDP-1",
})

hl.workspace_rule({
  workspace = "7",
  monitor = "eDP-1",
})

hl.workspace_rule({
  workspace = "8",
  monitor = "DP-7",
})

hl.workspace_rule({
  workspace = "9",
  monitor = "DP-7",
})

hl.workspace_rule({
  workspace = "10",
  monitor = "DP-7",
})

hl.window_rule({
  name = '"suppress maximize"',
  match = {
    class = "*",
  },
  suppress_event = "true",
  maximize = true,
})

hl.window_rule({
  name = '"XWayland dragging issues"',
  match = {
    class = '"^$"',
    title = '"^$"',
  },
  no_focus = true,
  -- xwayland = 1
  -- TODO: manual review — unmapped window rule action: "float on,"
  -- TODO: manual review — unmapped window rule action: "fullscreen 0,"
  pin = true,
})

hl.window_rule({
  name = '"float pulseaudio"',
  match = {
    class = "org.pulseaudio.pavucontrol",
    title = "Volume Control",
  },
  float = true,
  size = "960 480",
})

hl.window_rule({
  name = '"float bluetuith"',
  match = {
    class = "bluetuith",
  },
  -- idk why the title always fails to match
  -- match:title = bluetuith
  float = true,
  size = "480 480",
})

hl.env("GDK_SCALE", "2")
hl.env("XCURSOR_SIZE", "20")

hl.config({
  general = {
    --col.active_border = rgba(89b4faee) rgba(b4befeee) 45deg
    col = {
      active_border = colors.lavender,
      inactive_border = colors.surface1,
    },
    gaps_in = 0,
    gaps_out = 0,
    --gaps_out = 20, 20, 10, 20
    border_size = 4,
    -- https://wiki.hyprland.org/Configuring/Variables/#variable-types for info about colors
    --col.active_border = rgba(33ccffee) rgba(00ff99ee) 45deg
    --col.inactive_border = rgba(595959aa)
    -- Set to true enable resizing windows by clicking and dragging on borders and gaps
    resize_on_border = false,
    -- Please see https://wiki.hyprland.org/Configuring/Tearing/ before you turn this on
    allow_tearing = false,
    layout = "dwindle",
    snap = {
      enabled = true,
      --border_overlap = true
    },
  },
  -- the prior works super well btw dont even worry abt it
  -- https://wiki.hyprland.org/Configuring/Variables/#decoration
  decoration = {
    rounding = 0,
    rounding_power = 2,
    -- Change transparency of focused and unfocused windows
    --active_opacity = 1.0
    --inactive_opacity = 1.0
    --dim_inactive = false
    --dim_strength = 0.25
    border_part_of_window = false,
    shadow = {
      enabled = false,
      range = 4,
      render_power = 3,
      color = "rgba(1a1a1aee)",
    },
    -- https://wiki.hyprland.org/Configuring/Variables/#blur
    blur = {
      enabled = true,
      size = 3,
      passes = 1,
      vibrancy = 0.1696,
    },
  },
  -- https://wiki.hyprland.org/Configuring/Variables/#animations
  animations = {
    -- enabled = "yes, please :)",
    enabled = true,

    -- Default animations, see https://wiki.hyprland.org/Configuring/Animations/ for more
    --animation = windows, 1, 4.79, easeOutQuint
    --animation = windowsOut, 1, 10.49, linear, gnomed
    --animation = workspacesOut, 1, 1.94, almostLinear, fade
  },
  -- Ref https://wiki.hyprland.org/Configuring/Workspace-Rules/
  -- "Smart gaps" / "No gaps when only"
  -- See https://wiki.hyprland.org/Configuring/Dwindle-Layout/ for more
  dwindle = {
    -- pseudotile = true # Master switch for pseudotiling. Enabling is bound to mainMod + P in the keybinds section below
    preserve_split = true, -- You probably want this
  },
  -- See https://wiki.hyprland.org/Configuring/Master-Layout/ for more
  master = {
    new_status = "master",
  },
  -- https://wiki.hyprland.org/Configuring/Variables/#misc
  misc = {
    force_default_wallpaper = -1, -- Set to 0 or 1 to disable the anime mascot wallpapers
    disable_hyprland_logo = false, -- If true disables the random hyprland logo / anime girl background. :(
  },
  --############
  --## INPUT ###
  --############
  -- https://wiki.hyprland.org/Configuring/Variables/#input
  input = {
    kb_layout = "us",
    kb_variant = "",
    kb_model = "",
    kb_options = "",
    kb_rules = "",
    follow_mouse = 1,
    sensitivity = 0, -- -1.0 - 1.0, 0 means no modification.
    touchpad = {
      natural_scroll = false,
      scroll_factor = 0.3,
    },
  },
  -- Example per-device config
  -- See https://wiki.hyprland.org/Configuring/Keywords/#per-device-input-configs for more
  gestures = {
    workspace_swipe_distance = 1000,
  },
  --
  -- gesture = 3, horizontal, workspace
  -- unscale XWayland
  xwayland = {
    force_zero_scaling = true,
  },
  -- toolkit-specific scale
  -- windowrule {, class:org.pulseaudio.pavucontrol title:Volume Control }#float pulseaudio client
  --windowrule = float, class:org.pulseaudio.pavucontrol title:Volume Control #float pulseaudio client
  --start polkit
})

--################
--## AUTOSTART ###
--################
-- Autostart necessary processes (like notifications daemons, status bars, etc.)
-- Or execute your favorite apps at launch like this:

hl.on("hyprland.start", function()
  hl.exec_cmd("hypridle")
  hl.exec_cmd("fnott")
  hl.exec_cmd(terminal .. " -e fish -C fastfetch")
  hl.exec_cmd("wpaperd -d")
  -- exec-once = systemctl --user start hyprpolkitagent
  -- Start Hyprlock on startup to act as a pseudo Display Manager that is much faster
  hl.exec_cmd("hyprlock")
end)
